# 1. Datele de conectare
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate - MODUL DE DEZVOLTARE (Auto-generare)
# "update" creează tabelele lipsă sau adaugă coloane noi. 
# "create-drop" șterge și reface totul la fiecare repornire (curat, dar pierzi datele).
spring.jpa.hibernate.ddl-auto=validate

# Afișează în consolă ce SQL-uri execută Hibernate sub capotă
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# 3. DEZACTIVEAZĂ Flyway momentan (ca să nu se bată cu Hibernate)
spring.flyway.enabled=true

#4.JWT Security Configuration
jwt.secret=${JWT_SECRET}

# Expirare token: 12 ore
jwt.expiration=43200000

# Upload fișiere (filesystem local / volum montat)
sellbit.uploads.path=${SELLBIT_UPLOADS_PATH:/opt/sellbit/uploads}

# Upload nelimitat Spring Boot
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

