spring.application.name=backend

# Configurare H2 cu nume fix
spring.datasource.url=jdbc:h2:mem:sellbitdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Activare consolă
spring.h2.console.enabled=true
# Permite accesul la consolă fără erori de securitate (pentru testare locală)
spring.h2.console.settings.web-allow-others=true

# Hibernate - să creeze tabelele singur din clasele Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
